/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

/**
 *
 * @author gauge
 */
public class Inicio extends javax.swing.JFrame {
   
    private Login1 l1; //variable login para ocultar o mostrar la ventana
    
    Cambiar c1 = new Cambiar(); //inicializa cambiar para usar más tarde
    Despositar deposiotar = new Despositar(); //inicializa depositar para usar más tarde
    Retiro2 r2 = new Retiro2(); //inicializa retiro 2 para usar más tarde
    Bloquear b1oquear = new Bloquear();
    Cartola cartola = new Cartola();
    Transferir transferir = new Transferir();
    Consultar consultars = new Consultar();
    
    public Inicio() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void setL1(Login1 l1){ //set para obtener la variable
    this.l1=l1;
    }
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bloquear = new javax.swing.JButton();
        cambio = new javax.swing.JButton();
        cartolax = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        depositar = new javax.swing.JButton();
        retirar = new javax.swing.JButton();
        transferirx = new javax.swing.JButton();
        consultar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bloquear.setBackground(new java.awt.Color(217, 229, 241));
        bloquear.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        bloquear.setForeground(new java.awt.Color(51, 51, 51));
        bloquear.setText("Bloquear tarjeta");
        bloquear.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        bloquear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloquearActionPerformed(evt);
            }
        });
        jPanel1.add(bloquear, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 260, 180, 35));

        cambio.setBackground(new java.awt.Color(217, 229, 241));
        cambio.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        cambio.setForeground(new java.awt.Color(51, 51, 51));
        cambio.setText("Cambio PIN");
        cambio.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        cambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambioActionPerformed(evt);
            }
        });
        jPanel1.add(cambio, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, 180, 35));

        cartolax.setBackground(new java.awt.Color(217, 229, 241));
        cartolax.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        cartolax.setForeground(new java.awt.Color(51, 51, 51));
        cartolax.setText("Cartola");
        cartolax.setActionCommand("");
        cartolax.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        cartolax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cartolaxActionPerformed(evt);
            }
        });
        jPanel1.add(cartolax, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 160, 180, 35));

        jButton5.setBackground(new java.awt.Color(217, 229, 241));
        jButton5.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 51));
        jButton5.setText("Salir");
        jButton5.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 180, 35));

        depositar.setBackground(new java.awt.Color(217, 229, 241));
        depositar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        depositar.setForeground(new java.awt.Color(51, 51, 51));
        depositar.setText("Depositar");
        depositar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        depositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                depositarActionPerformed(evt);
            }
        });
        jPanel1.add(depositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 160, 180, 35));

        retirar.setBackground(new java.awt.Color(217, 229, 241));
        retirar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        retirar.setForeground(new java.awt.Color(51, 51, 51));
        retirar.setText("Retirar");
        retirar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        retirar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                retirarActionPerformed(evt);
            }
        });
        jPanel1.add(retirar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 180, 35));

        transferirx.setBackground(new java.awt.Color(217, 229, 241));
        transferirx.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        transferirx.setForeground(new java.awt.Color(51, 51, 51));
        transferirx.setText("Transferencia");
        transferirx.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        transferirx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transferirxActionPerformed(evt);
            }
        });
        jPanel1.add(transferirx, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 310, 180, 35));

        consultar.setBackground(new java.awt.Color(217, 229, 241));
        consultar.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 18)); // NOI18N
        consultar.setForeground(new java.awt.Color(51, 51, 51));
        consultar.setText("Consultar saldo");
        consultar.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), null));
        consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                consultarActionPerformed(evt);
            }
        });
        jPanel1.add(consultar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, 180, 35));

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jLabel7.setMaximumSize(new java.awt.Dimension(850, 1965));
        jLabel7.setMinimumSize(new java.awt.Dimension(500, 500));
        jLabel7.setPreferredSize(new java.awt.Dimension(500, 500));
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(-12, 0, 810, 699));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bloquearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloquearActionPerformed
        b1oquear.setI1(this);
        b1oquear.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_bloquearActionPerformed

    private void cambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambioActionPerformed
        c1.setI1(this);
        c1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cambioActionPerformed

    private void cartolaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cartolaxActionPerformed
        cartola.setI1(this);
        cartola.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_cartolaxActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void depositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_depositarActionPerformed
        deposiotar.setI1(this);
        depositar.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_depositarActionPerformed

    private void retirarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_retirarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_retirarActionPerformed

    private void transferirxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transferirxActionPerformed
        transferir.setI1(this);
        transferir.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_transferirxActionPerformed

    private void consultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_consultarActionPerformed
        consultars.setI1(this);
        consultars.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_consultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bloquear;
    private javax.swing.JButton cambio;
    private javax.swing.JButton cartolax;
    private javax.swing.JButton consultar;
    private javax.swing.JButton depositar;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton retirar;
    private javax.swing.JButton transferirx;
    // End of variables declaration//GEN-END:variables
}
