/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista;

import java.util.Date;
import javax.swing.JTextField;
import com.toedter.calendar.JDateChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author gauge
 */
public class Registrar1 extends javax.swing.JFrame {
   
    private Login1 l1; //variable login para ocultar o mostrar la ventana
 //   Registrar2 v2 = new Registrar2(); //inicializa registro 2 para usar más tarde
    String run;
    public Registrar1() {
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    public void setL1(Login1 l1){ //set para obtener la variable
        this.l1=l1;
    }
 
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        cecivil = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        cnombre = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        crun = new javax.swing.JTextField();
        cemail = new javax.swing.JTextField();
        Botonatras1 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        Botonsiguiente = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        cmasculino = new javax.swing.JRadioButton();
        cfemenino = new javax.swing.JRadioButton();
        cnobinario = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cnacimiento = new com.toedter.calendar.JDateChooser();
        csueldo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Fecha Nac: ");

        cecivil.setBackground(new java.awt.Color(255, 255, 255));
        cecivil.setEditable(true);
        cecivil.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        cecivil.setForeground(new java.awt.Color(0, 0, 0));
        cecivil.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar", "Soltero(a)", "Casado(a)", "Divorsiado(a)", "Viudo(a)" }));
        cecivil.setFocusable(false);
        cecivil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cecivilActionPerformed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Estado Civil:");

        cnombre.setBackground(new java.awt.Color(255, 255, 255));
        cnombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cnombreActionPerformed(evt);
            }
        });

        jLabel8.setBackground(new java.awt.Color(255, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("E-mail:");

        crun.setBackground(new java.awt.Color(255, 255, 255));
        crun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crunActionPerformed(evt);
            }
        });

        cemail.setBackground(new java.awt.Color(255, 255, 255));

        Botonatras1.setBackground(new java.awt.Color(0, 0, 0));
        Botonatras1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Botonatras1.setForeground(new java.awt.Color(255, 255, 255));
        Botonatras1.setText("ATRAS");
        Botonatras1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Botonatras1ActionPerformed(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(255, 255, 255));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("  Sueldo:");

        Botonsiguiente.setBackground(new java.awt.Color(0, 0, 0));
        Botonsiguiente.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        Botonsiguiente.setForeground(new java.awt.Color(255, 255, 255));
        Botonsiguiente.setText("SIGUIENTE");
        Botonsiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonsiguienteActionPerformed(evt);
            }
        });

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("RUN:");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI Black", 0, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Formulario de aplicación");

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 102, 102));
        jLabel3.setText("Datos personales");

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        buttonGroup1.add(cmasculino);
        cmasculino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmasculino.setForeground(new java.awt.Color(51, 51, 51));
        cmasculino.setText("Masculino");
        cmasculino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmasculinoActionPerformed(evt);
            }
        });

        buttonGroup1.add(cfemenino);
        cfemenino.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cfemenino.setForeground(new java.awt.Color(51, 51, 51));
        cfemenino.setText("Femenino");
        cfemenino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cfemeninoActionPerformed(evt);
            }
        });

        buttonGroup1.add(cnobinario);
        cnobinario.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cnobinario.setForeground(new java.awt.Color(51, 51, 51));
        cnobinario.setText("No binario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(cmasculino)
                .addGap(50, 50, 50)
                .addComponent(cfemenino)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(cnobinario)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cmasculino)
                    .addComponent(cfemenino)
                    .addComponent(cnobinario))
                .addContainerGap())
        );

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Nombre completo:");

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Genero:");

        cnacimiento.setBackground(new java.awt.Color(255, 255, 255));
        cnacimiento.setForeground(new java.awt.Color(255, 255, 255));
        cnacimiento.setDateFormatString("dd-MM-yyyy");
        cnacimiento.setMinSelectableDate(new java.util.Date(-62135751540000L));
        cnacimiento.setOpaque(false);

        csueldo.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(81, 81, 81)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cemail, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cnombre, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(crun, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cecivil, javax.swing.GroupLayout.Alignment.LEADING, 0, 375, Short.MAX_VALUE)
                            .addComponent(cnacimiento, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(csueldo)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(Botonatras1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 352, Short.MAX_VALUE)
                        .addComponent(Botonsiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(71, 71, 71))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabel13))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel3)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cnombre, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(crun, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(cnacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cecivil, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cemail, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(csueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Botonsiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Botonatras1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cnombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnombreActionPerformed

    private void Botonatras1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Botonatras1ActionPerformed
        l1.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Botonatras1ActionPerformed

    private void BotonsiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonsiguienteActionPerformed
        
        
        String genero = null;        
        // String id_cliente = "" + random; // 1
        String name = cnombre.getText(); // 2
        String run = crun.getText();
        String email = cemail.getText();
        String ecivil = (String) cecivil.getSelectedItem();
        String fNacimiento = ((JTextField) cnacimiento.getDateEditor().getUiComponent()).getText(); // 9   
        String sueldo2 = csueldo.getText();
        
        if (cmasculino.isSelected()) {
            genero = "masculino";
        } else if (cfemenino.isSelected()) {
            genero = "femenino";
        } else if (cnobinario.isSelected()) {
            genero = "No binario";
        } 
        else{ genero = "";}
        if (name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese nombre", "Validación", JOptionPane.WARNING_MESSAGE);
            this.cnombre.requestFocus();
            return;
        }else if(run.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese run", "Validación", JOptionPane.WARNING_MESSAGE);
            this.crun.requestFocus();
            return;
        }else if (genero.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese su genero", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
            
        }else if (fNacimiento.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese fecha nacimiento", "Validación", JOptionPane.WARNING_MESSAGE);
            return;
            
        }else if (ecivil.equalsIgnoreCase("Seleccionar")) {
            JOptionPane.showMessageDialog(this, "Ingrese estado civil", "Validación", JOptionPane.WARNING_MESSAGE);
            this.cecivil.requestFocus();
            return;
            
        }else if (email.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese email", "Validación", JOptionPane.WARNING_MESSAGE);
            this.cemail.requestFocus();
            return;    
            
         
        }else if (sueldo2.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Ingrese su sueldo", "Validación", JOptionPane.WARNING_MESSAGE);
            this.csueldo.requestFocus();
            return;

        }
        
            else{

  

      
        Integer sueldo = Integer.valueOf(sueldo2); // 11
        
        Registrar2 v2 = new Registrar2(name,run,sueldo,genero,email,ecivil,fNacimiento);

        v2.setV1(this);
        v2.setVisible(true);
        this.setVisible(false);
                    }

//boton siguiente:

    }//GEN-LAST:event_BotonsiguienteActionPerformed
    
    private void crunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_crunActionPerformed

    private void cecivilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cecivilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cecivilActionPerformed

    private void cmasculinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmasculinoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmasculinoActionPerformed

    private void cfemeninoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cfemeninoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cfemeninoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Registrar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Registrar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Registrar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Registrar1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Registrar1().setVisible(true);
            }
        });
    }




    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Botonatras1;
    private javax.swing.JButton Botonsiguiente;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cecivil;
    private javax.swing.JTextField cemail;
    private javax.swing.JRadioButton cfemenino;
    private javax.swing.JRadioButton cmasculino;
    private com.toedter.calendar.JDateChooser cnacimiento;
    private javax.swing.JRadioButton cnobinario;
    private javax.swing.JTextField cnombre;
    private javax.swing.JTextField crun;
    private javax.swing.JTextField csueldo;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
